### ISSUE TITLE
jupyter ERROR：

### ISSUE THREAD

**Issue by WeiSong123** [ufoym/deepo#28] opened 2018-03-30 02:40 UTC
usage: ipykernel_launcher.py [-h] [--batch-size N] [--test-batch-size N]
                             [--epochs N] [--lr LR] [--momentum M] [--no-cuda]
                             [--seed S] [--log-interval N]
ipykernel_launcher.py: error: unrecognized arguments: -f /root/.local/share/jupyter/runtime/kernel-8d4d68c2-c1a5-4176-83d3-6d030e7d6e33.json

An exception has occurred, use %tb to see the full traceback.

SystemExit: 2

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2918: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

**Comment by ufoym** [comment] 2018-04-03 01:44
@WeiSong123 Could you provide the exact command to reproduce this problem?

**Comment by ufoym** [comment] 2018-05-02 08:10
Close this issue as we cannot reproduce the problem you have reported. If anyone finds that the problem still exists, feel free to reopen it.

**Closed by ufoym** 2018-05-02 08:10 UTC

**Comment by ufoym** [comment] 2018-05-15 11:34
@WeiSong123 

We guess the exception was raised when executing argparse in IPython console.
Try
```
import sys; sys.argv=['']; del sys
```
before
```
parser.parse_args()
```
